### PR TITLE
Add extra instructions to readme to help get setup faster

### PR DESCRIPTION
**Pull request by Holdrick**
Contributes to # (add issue number here. i.e. `#302`)

## What did you do?
Added instructions for what to put in the .env file
Added link to video showing how to setup IBM App ID
Added comment about forking before cloning
## Why did you do it?
To help make setup a little smoother so people don't encounter issues I did
## How have you tested it?
I was able to get the API up and running with the newly modified steps in the readme
## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [x] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new console logs
- [ ] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Review by kayleekimberly — APPROVED** [review]
These additions looks great!

**Comment by upkarlidder** [comment]
@Holdrick, which libraries are not supported? We should list them and point to their docs for supported platforms.

**Comment by Holdrick** [comment]
> @Holdrick, which libraries are not supported? We should list them and point to their docs for supported platforms.

The one I came across was uvloop. I'll add some detail for it

**Review by naagma5 — COMMENTED** [review]
Adding the video will be very helpful! Great add along with the other updates to the tutorial.

**Review by upkarlidder — APPROVED** [review]
LGTM. Thank you for your work @Holdrick

**Pull request merged**
