### PR TITLE
Add super-linter as a GitHub action

### PR DESCRIPTION
**Pull request by nic-jol**
Contributes to #41

## What did you do?
Added GitHub action to run super-linter (https://github.com/marketplace/actions/super-linter) whenever changes are pushed or a pull request is created.
## Why did you do it?
As part of creating a CI/CD process, we want to have a linter to verify the formatting of contributed files.
## How have you tested it?
1. On Push example: https://github.com/nic-jol/TakeTwo-WebAPI/runs/5313744282?check_suite_focus=true#step:4:64
2. On a Pull Request example: https://github.com/nic-jol/TakeTwo-WebAPI/pull/1

## Were docs updated if needed?
Unsure if any docs need to be updated
- [X] No
- [ ] Yes
- [ ] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new console logs
- [X] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by nic-jol** [comment]
I committed some of these changes just by editing it through the GitHub GUI which apparently did not sign the commit. I'm not sure if I'm able to fix this.

**Comment by demilolu** [comment]
@nic-jol we discussed and think this is an appropriate solution for now. please go ahead.

**Comment by nic-jol** [comment]
> I committed some of these changes just by editing it through the GitHub GUI which apparently did not sign the commit. I'm not sure if I'm able to fix this.

I fixed this issue and the DCO check should now pass.

**Review by upkarlidder — APPROVED** [review]
Approving to see if this works. We might need to add some more config if this takes too long.

**Pull request merged**
